---
title: "09.데이터분석 프로젝트 - 한국인의 삶을 파악하라"
author: "성상모"
output:
  html_document:
    toc: true
    toc_float: true
mainfont: NanumGothic
fontsize: 12pt
lang: Korean
---
```{r include=F}
# global option
knitr::opts_chunk$set(
  comment = "##>",
  collapse = T,
  eval = T,
  tidy = F,
  message = F,
  warning = F
)
```
---  

## 9-1 한국복지패널데이터 불러오기

```{r}
library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)

# 데이터 불러오기
raw_welfare <- read.spss(file = "../data/Koweps_hpc10_2015_beta1.sav", to.data.frame = T)

# 복사본 만들기
welfare <- raw_welfare

# 데이터 검토하기
str(welfare)
dim(welfare)

# 변수명 바꾸기
welfare <- rename(welfare,
                  sex = h10_g3,
                  birth = h10_g4,
                  marriage = h10_g10,
                  religion = h10_g11,
                  income = p1002_8aq1,
                  code_job = h10_eco9,
                  code_region = h10_reg7)
```

## 9-2 성별에 따른 월급 차이 - 성별에 따라 월급이 다를까? 

```{r}
# 변수 검토하기
class(welfare$sex)

# 이상치 확인
table(welfare$sex)

# 이상치 결측 처리
welfare$sex <- ifelse(welfare$sex == 9, NA, welfare$sex)

# 결측치 확인
table(is.na(welfare$sex))
```

```{r, fig.width=4, fig.height=4}
# 성별 항목 이름 부여
welfare$sex <- ifelse(welfare$sex == 1, "male", "female")
table(welfare$sex)

qplot(welfare$sex)
```

```{r}
library(foreign)

# 변수 검토하기
class(welfare$income)

# 이상치 확인
summary(welfare$income)

# 이상치 결측 처리
welfare$income <- ifelse(welfare$income %in% c(0, 9999), NA, welfare$income)

# 결측치 확인
table(is.na(welfare$income))
```

```{r}
# 성별 월급 평균표 만들기
sex_income <- welfare %>% 
   filter(!is.na(income)) %>% 
   group_by(sex) %>% 
   summarise(mean_income = mean(income))

sex_income
```

```{r, fig.width=4, fig.height=4}
ggplot(data = sex_income, aes(x = sex, y = mean_income)) + geom_col()
```


## 9-3 나이와 월급의 관계 - 몇 살 때 월급을 가장 많이 받을까? 

```{r, fig.width=4, fig.height=4}
class(welfare$birth)

summary(welfare$birth)

qplot(welfare$birth)
```

```{r}
# 전처리
summary(welfare$birth)

# 결측치 확인
table(is.na(welfare$birth))

# 이상치 결측 처리
welfare$birth <- ifelse(welfare$birth == 9999, NA, welfare$birth)
table(is.na(welfare$birth))
```

```{r, fig.width=4, fig.height=4}
# 파생변수 만들기
welfare$age <- 2015 - welfare$birth + 1
summary(welfare$age)

qplot(welfare$age)
```


```{r}
age_income <- welfare %>% 
   filter(!is.na(income)) %>% 
   group_by(age) %>% 
   summarise(mean_income = mean(income))

head(age_income)
```

```{r, fig.width=4, fig.height=4}
ggplot(data = age_income, aes(x = age, y = mean_income)) + geom_line()
```

